# This is a basic workflow to help you get started with Actions

name: publish

on:
  push:
    branches: [ dev ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Run install pnpm
        run: npm i -g pnpm

      - name: Run install
        run: pnpm install --no-frozen-lockfile

      - name: Run build
        run: pnpm build:lib

      - name: Run test
        run: pnpm test
      - name: Run codecov
        run: npx codecov --token=${{ secrets.CODECOV_TOKEN }}

